services:
  receipt-app:
    ports: !override []
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.ctp500.rule=Host(`ctp500.example.com`)"
      - "traefik.http.routers.ctp500.entryPoints=https"
      - "traefik.http.routers.ctp500.tls=true"
      - "traefik.http.routers.ctp500.tls.certresolver=le"
      - "traefik.http.routers.ctp500.service=ctp500-entrypoint"
      - "traefik.http.services.ctp500-entrypoint.loadbalancer.server.port=8080"
    networks:
      - traefik

networks:
  traefik:
    external: true
